tasks:
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    before:
      # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
      # Run validate configuration
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

