#!/usr/bin/env bash

echo "== list objects =="

if [ -z "$1" ]; then
    echo "There is no bucket name provided. eg ./list-objects my-new-bucket"
    exit 1
fi

## https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-bucket.html

aws s3api list-objects-v2 \
--bucket $1 \
--query 'Contents[].{Key: Key, Size: Size, LastModified: LastModified}' \
--output table