#!/usr/bin/env bash

echo "== put objects =="

if [ -z "$1" ]; then
    echo "There is no bucket name provided. eg ./put-objects.sh my-new-bucket"
    exit 1
fi

if [ -z "$2" ]; then
    echo "You must provide the filename. eg ./sync my-new-bucket example-object.txt"
    exit 1
fi

FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

mkdir -p ./tmp
echo "Creating a sample object in the tmp directory..."
echo "This is a sample object." > ./tmp/${FILENAME}
echo "Uploading the sample object to the S3 bucket..."


aws s3api put-object \
--bucket $1 \
--key $OBJECT_KEY \
--body ./tmp/${FILENAME} \

echo "Object uploaded successfully."
echo "Cleaning up temporary files..."
rm -r ./tmp
